---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUA2XZQeD2IN9XjwZuD31yeCtUI+4wCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUxMTA2MDE1NDAwWhcNNDAxMTAyMDE1NDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGiE
          UZtR0AsOoUU/SXqXH88uYCD1UFm0J8qHm1Qyvg9wZG6kDkpTLgRcH+E9Lnbtcl7l
          zneHw7hXm5RKmOGnsxajRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSLHpBGzN/MblD6E9Bim993XgZMzzAKBggqhkjOPQQD
          AgNHADBEAiAWmZRsT136Eduwk6MW69RJ2/DPxk6CAnmZeLSy39aAFwIgE8W4d7So
          Su4Vql2Kc1TnJH5GWoyKZNik8qd/TOCMvFc=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICJjCCAc2gAwIBAgIUA2XZQeD2IN9XjwZuD31yeCtUI+4wCgYIKoZIzj0EAwIw
          cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
          EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjUxMTA2MDE1NDAwWhcNNDAxMTAyMDE1NDAw
          WjBwMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExDzANBgNV
          BAcTBkR1cmhhbTEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMT
          Y2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGiE
          UZtR0AsOoUU/SXqXH88uYCD1UFm0J8qHm1Qyvg9wZG6kDkpTLgRcH+E9Lnbtcl7l
          zneHw7hXm5RKmOGnsxajRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAG
          AQH/AgEBMB0GA1UdDgQWBBSLHpBGzN/MblD6E9Bim993XgZMzzAKBggqhkjOPQQD
          AgNHADBEAiAWmZRsT136Eduwk6MW69RJ2/DPxk6CAnmZeLSy39aAFwIgE8W4d7So
          Su4Vql2Kc1TnJH5GWoyKZNik8qd/TOCMvFc=
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
