version: '3.7'

volumes:
  orderer.union.gov:
  peer0.union.gov:
  ca.union.gov:

networks:
  fabric-network:
    name: fabric-network

services:
  # Certificate Authority for Union
  ca.union.gov:
    image: hyperledger/fabric-ca:1.5.7
    container_name: ca.union.gov
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.union.gov
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ca.union.gov:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric-network

  # Orderer for the network
  orderer.union.gov:
    image: hyperledger/fabric-orderer:2.5.4
    container_name: orderer.union.gov
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=UnionOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.union.gov:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ./organizations/ordererOrganizations/union.gov/orderers/orderer.union.gov/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/union.gov/orderers/orderer.union.gov/tls:/var/hyperledger/orderer/tls
      - orderer.union.gov:/var/hyperledger/production/orderer
      - ./channel-artifacts:/var/hyperledger/channel-artifacts
    ports:
      - "7050:7050"
      - "7053:7053"
      - "9443:9443"
    networks:
      - fabric-network
    depends_on:
      - ca.union.gov

  # Union Peer
  peer0.union.gov:
    image: hyperledger/fabric-peer:2.5.4
    container_name: peer0.union.gov
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-network
      - CORE_PEER_ID=peer0.union.gov
      - CORE_PEER_ADDRESS=peer0.union.gov:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.union.gov:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.union.gov:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.union.gov:7051
      - CORE_PEER_LOCALMSPID=UnionMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_OPERATIONS_LISTENADDRESS=peer0.union.gov:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0union"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./organizations/peerOrganizations/union.gov/peers/peer0.union.gov/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/union.gov/peers/peer0.union.gov/tls:/etc/hyperledger/fabric/tls
      - peer0.union.gov:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "7051:7051"
      - "9444:9444"
    networks:
      - fabric-network
    depends_on:
      - ca.union.gov

  # CLI tool for interacting with the network
  cli:
    image: hyperledger/fabric-tools:2.5.4
    container_name: cli
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.union.gov:7051
      - CORE_PEER_LOCALMSPID=UnionMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/union.gov/peers/peer0.union.gov/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/union.gov/peers/peer0.union.gov/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/union.gov/peers/peer0.union.gov/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/union.gov/users/Admin@union.gov/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
    networks:
      - fabric-network
    depends_on:
      - peer0.union.gov
      - orderer.union.gov