Organizations:
  - &UnionOrderer
    Name: UnionOrdererMSP
    ID: UnionOrdererMSP
    MSPDir: ../organizations/ordererOrganizations/union.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('UnionOrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('UnionOrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('UnionOrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.union.gov:7050

  - &Union
    Name: UnionMSP
    ID: UnionMSP
    MSPDir: ../organizations/peerOrganizations/union.gov/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('UnionMSP.admin', 'UnionMSP.peer', 'UnionMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('UnionMSP.admin', 'UnionMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('UnionMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('UnionMSP.peer')"
    AnchorPeers:
      - Host: peer0.union.gov
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.union.gov:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.union.gov
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/union.gov/orderers/orderer.union.gov/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/union.gov/orderers/orderer.union.gov/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  UnionChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *UnionOrderer
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Union
      Capabilities:
        <<: *ApplicationCapabilities